# Generated by Django 5.2.7 on 2025-10-29 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255, unique=True)),
                ('nombre_comercial', models.CharField(max_length=255, unique=True)),
                ('tipo_documento', models.CharField(choices=[('CEDULA', 'Cédula'), ('RUC', 'RUC')], default='CEDULA', max_length=20)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('direccion', models.TextField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('tipo_banco', models.CharField(max_length=150, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('observaciones', models.CharField(max_length=150)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proveedores/')),
                ('canton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.canton')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.provincia')),
            ],
        ),
    ]
