# Generated by Django 5.2.7 on 2025-11-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0002_supplier_cedula_ruc_dueno_supplier_dueno_cuenta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25, unique=True)),
                ('rubro', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('suppliers', models.ManyToManyField(related_name='products', to='suppliers.supplier')),
            ],
        ),
    ]
