# Generated by Django 5.2.7 on 2025-11-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='estado',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('BAJO', 'Bajo'), ('SIN_STOCK', 'Sin Stock')], default='NORMAL', max_length=20),
        ),
    ]
